build:
  image: default-bionic    
  environment:
        node: v16
  nodes:
    analysis:
      project_setup:
        override: true
      tests:
        override:
          - php-scrutinizer-run --enable-security-analysis

checks:
  php:
    code_rating: true
    duplication: true

filter:
  paths: ["src/*"]
